name: tiebaSign

on:
   push:
   workflow_dispatch:
   schedule:
       - cron: '37 0 * * *'
       - cron: '23 5 * * *'

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Sign in
        env:
          BDUSS: ${{ secrets.BDUSS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: go run .
